services:
  simplejobbot-app:
    build: .
    container_name: simplejobbot-app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_HOST=http://simplejobbot-ollama:11434
      - JOBBOT_MODEL=llama3.2:3b
    volumes:
      - ./job-packages:/app/job-packages
    depends_on:
      - simplejobbot-ollama

  simplejobbot-ollama:
    image: ollama/ollama:latest
    container_name: simplejobbot-ollama
    ports:
      - "11434:11434"
    volumes:
      - ./ollama:/root/.ollama
    entrypoint: ["ollama", "serve"]
